version: '3.9'
services:

  dns-server:
    image: strm/dnsmasq
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      - backend

  balancer:
    image: nginx:latest
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./images/:/data/images
    networks:
      default:
        ipv4_address: 172.16.0.10


networks:
  backend:
    driver: bridge
