version: '3.9'
services:

  binddns:
    build:
      context: ./bind
    environment:
      - WEBMIN_ENABLED=false
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - bind_data:/data
      - ./bind/logs:/var/log/named
    networks:
      cdn_network:
        ipv4_address: 172.18.0.12

  edge:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/edge.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cdn_network

  us-balancer:
    image: nginx:latest
    ports:
      - 8082:80
    volumes:
     - ./nginx/us/balancer.conf:/etc/nginx/conf.d/default.conf
    networks:
      cdn_network:
        ipv4_address: 172.18.0.13

  global-balancer:
    image: nginx:latest
    volumes:
      - ./nginx/global/balancer.conf:/etc/nginx/conf.d/default.conf
    networks:
      cdn_network:
        ipv4_address: 172.18.0.14

  us-node1:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./images/us/:/data/images
    networks:
      - cdn_network

  us-node2:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./images/us/:/data/images
    networks:
      - cdn_network

  global-node1:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./images/global/:/data/images
    networks:
      - cdn_network

  global-node2:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./images/global/:/data/images
    networks:
      - cdn_network

volumes:
  bind_data:

networks:
  cdn_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24  # Specify the subnet for the network